Part15 - Background tasks
TimmyMT/qna pull request #12
Opened 2019-10-13 08:21 UTC by TimmyMT

2019-10-14 06:38 UTC, aishek requested changes
Первый подход сделан: всё работает. Нужно поработать над деталями.

2019-10-14 06:38 UTC, aishek commented on app/models/answer.rb
> +  after_commit :subscriptions_notification
Лучше называть не существительным, а глаголом: `notify_subscribers`

2019-10-14 06:38 UTC, aishek commented on app/models/subscription.rb
> +class Subscription < ApplicationRecord
Тут полезно добавить защиту от двойной подписки.

2019-10-14 06:38 UTC, aishek commented on app/views/daily_mailer/digest.html.slim
> +- @questions.each do |question|
Лучше `find_each`

2019-10-14 06:38 UTC, aishek commented on app/views/daily_mailer/digest.text.slim
> +- @questions.each do |question|
Лучше `find_each`

2019-10-14 06:38 UTC, aishek commented on config/schedule.rb
> +  runner "DailyDigestJob.perform_now"
Почему тут сразу сервис не запустить?

2019-10-14 06:38 UTC, aishek commented on app/models/user.rb
> +  def self.send_daily_digest
Эта задача к пользователю относится весьма опосредованно. Лучше вынести в отдельный сервис

2019-10-14 06:38 UTC, aishek commented on app/models/ability.rb
> +
Настораживает обратная логика

2019-10-14 06:38 UTC, aishek commented on app/models/concerns/subscribable.rb
> +    subscriptions.create(user: user)
Лучше метод назвать с восклицательным знаком в конце и использовать `create!`, ведь не ожидается что тут что-то сломается

2019-10-14 06:38 UTC, aishek commented on app/models/concerns/subscribable.rb
> +  def unsubscribe(user)
Я бы назвал метод с восклицательным знаком, так как внутри в теории может быть ошибка, если не найдётся подписка

2019-10-14 06:38 UTC, aishek commented on app/models/concerns/subscribable.rb
> +  def subscribed?(user)
Такой метод по соглашениям должен вернуть `true` или `false`, а он возвращает объект или `nil`. Чтобы это исправить можно использовать `.present?`

2019-10-14 06:38 UTC, aishek commented on app/views/questions/_question.html.slim
> +    = link_to 'Sub', subscribe_question_path, method: :post
Логику лучше выпрямить, сейчас обратная

2019-10-14 06:38 UTC, aishek commented on config/routes.rb
> +  resources :questions, shallow: true, concerns: [:votable, :subscribable] do
Мне больше нравится идея посвятить подпискам отдельный контроллер.

2019-10-14 06:38 UTC, aishek commented on spec/controllers/concerns/subscribed.rb
> +shared_examples_for "subscribed" do
Тут нужно проверить неавторизованного и уже подписанного/неподписанного соответственно

2019-10-14 06:38 UTC, aishek commented on spec/jobs/answer_notification_job_spec.rb
> +  let(:user) { create(:user) }
Хорошо бы ещё неподписанного пользователя создать и проверить что его нет в рассылке

2019-10-14 06:38 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +  describe "digest" do
Тут нужно проверить что только нужные вопросы попали в рассылку

2019-10-14 06:38 UTC, aishek commented on spec/models/concerns/subscribable.rb
> +  describe '#unsubscribe(user)' do
Нужно проверить вызов на неподписанном

2019-10-14 06:38 UTC, aishek commented on spec/models/concerns/subscribable.rb
> +  describe '#subscribe(user)' do
Нужно проверить вызов на уже подписанном

2019-10-14 06:38 UTC, aishek commented on spec/features/questions/subscribe_question_spec.rb
> +feature 'subscribe to a question' do
Надо проверить что автор после создания вопроса сразу на него подписан, и что он может от него отписаться

2019-10-14 20:18 UTC, aishek requested changes
Очень много замечаний и пожеланий с прошлого раза не отработаны.

2019-10-14 20:18 UTC, aishek commented on app/models/concerns/subscribable.rb
> +  def subscribed?(user)
Замечание не исправлено

2019-10-14 20:18 UTC, aishek commented on app/controllers/subscriptions_controller.rb
> +    @resource.subscribe(current_user)
С появлением этого контроллера стало очевидно, что не нужны `subscribe` и `unsubscribe`, так как они повторяют `create` и `destroy` соответственно.

2019-10-14 20:18 UTC, aishek commented on app/models/ability.rb
> +      sub.question.subsribed?(user)
Опечатка. И почему просто не проверить пользователя?

2019-10-14 20:18 UTC, aishek commented on app/models/answer.rb
> +  def subscribers_notification
Название по-английски звучит как существительное, а не глагол. А нужен глагол.

2019-10-14 20:18 UTC, aishek commented on app/models/concerns/subscribable.rb
> +  def unsubscribe(user)
Замечание не исправлено, но метод уже не нужен

2019-10-14 20:18 UTC, aishek commented on app/models/user.rb
> +  # def self.send_daily_digest
Закомментированный код нужно удалять

2019-10-14 20:18 UTC, aishek commented on app/views/questions/_question.html.slim
> +      = link_to 'Unsub', subscription_path(question.subscribed?(current_user)), method: :delete
Зачем тут в скобках вызывается `question.subscribed?(current_user)`?

2019-10-14 20:18 UTC, aishek commented on config/schedule.rb
> +  runner "DailyDigestJob.perform_now"
Вопрос остался

2019-10-14 20:18 UTC, aishek commented on app/services/daily_digest.rb
> +    User.find_each(batch_size: 500) do |user|
Без особой надобности не надо переопределять `batch_size`

2019-10-14 20:18 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +  describe "digest" do
Вопрос остался

2019-10-14 20:18 UTC, aishek commented on spec/models/subscription_spec.rb
> +  it 'uniqueness validate' do
Почему не использовать матчер?

2019-10-14 20:18 UTC, aishek commented on spec/features/questions/subscribe_question_spec.rb
> +feature 'subscribe to a question' do
Вопрос остался

2019-10-14 20:18 UTC, aishek commented on app/controllers/subscriptions_controller.rb
> +class SubscriptionsController < ActionController::Base
На этот контроллер нужны тесты.

2019-10-15 16:55 UTC, aishek requested changes

2019-10-15 16:55 UTC, aishek commented on app/models/ability.rb
> +    can :destroy, Subscription do |sub|
Можно было добавить в 29 строку

2019-10-15 16:55 UTC, aishek commented on app/models/ability.rb
> +    can :destroy, Subscription do |sub|
И локальную переменную лучше не сокращать

2019-10-15 16:55 UTC, aishek commented on app/models/question.rb
> +    self.subscriptions.where(user: user).present?
Почему не `find_by`?

2019-10-15 16:55 UTC, aishek commented on app/views/daily_mailer/digest.html.slim
> +- @questions.each do |question|
Замечание осталось

2019-10-15 16:55 UTC, aishek commented on app/views/daily_mailer/digest.text.slim
> +- @questions.each do |question|
Замечание осталось

2019-10-15 16:55 UTC, aishek commented on app/views/questions/_question.html.slim
> +      = link_to 'Unsub', subscription_path(question.id), method: :delete
Можно проще: `= link_to 'Unsub', subscription_path(question), method: :delete`

2019-10-15 16:55 UTC, aishek commented on db/migrate/20191015090438_delete_f_key_from_subscription.rb
> +    drop_table :subscriptions
Жёстко :)

2019-10-15 16:55 UTC, aishek commented on spec/controllers/subscriptions_controller_spec.rb
> +        question.subscriptions.create(user: user)
Это нужно в `let`

2019-10-15 16:55 UTC, aishek commented on spec/controllers/subscriptions_controller_spec.rb
> +  describe 'Guest' do
Лучше группировка наоборот: внутри метода авторизованный и неавторизованный пользователь.

2019-10-15 16:55 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +      Question.where('created_at < ?', 1.day.ago).each do |question|
Ставлю на то, что таких вопросов в этом тесте нет. Надо создать.

А ещё тут же проверить что нужные вопросы есть

2019-10-15 16:55 UTC, aishek commented on spec/models/question_spec.rb
> +      expect(Subscription.count).to be > before_sub
Очень хорошо, что этот тест есть. Но надо точнее: проверить что на `+1` количество поменялось

2019-10-15 16:55 UTC, aishek commented on spec/models/question_spec.rb
> +      expect(question.subscribed?(other_user)).to be_falsey
Тут лучше использовать https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-10-15 17:04 UTC, TimmyMT commented on db/migrate/20191015090438_delete_f_key_from_subscription.rb
> +    drop_table :subscriptions
Не мог найти как ремувнуть ключ, позже уже нашёл, а миграцию менять лень было)

2019-10-15 18:14 UTC, aishek requested changes

2019-10-15 18:14 UTC, aishek commented on app/models/ability.rb
> +    # can :destroy, Subscription do |sub|
Закомментированный код нужно удалять

2019-10-15 18:14 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +                                created_at: question.created_at - 1.day) }
Можно `2.days.ago`

2019-10-15 18:14 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +      Question.where('created_at < ?', 1.day.ago).each do |question|
Вторая часть замечания остаётся

2019-10-16 07:29 UTC, aishek approved these changes

2019-10-16 07:29 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +                                created_at: question.created_at - 2.days.ago) }
Просто `created_at: 2.days.ago`

2019-10-16 07:29 UTC, aishek commented on spec/mailers/daily_mailer_spec.rb
> +      Question.where('created_at < ?', 1.day.ago).each do |question|
Вообще лучше явно проверить для `question` и `old_question`

2019-10-16 10:50 UTC, merged