Part9 - Nested Forms
TimmyMT/qna pull request #5
Opened 2019-09-17 12:10 UTC by TimmyMT

2019-09-19 08:39 UTC, aishek requested changes

2019-09-19 08:39 UTC, aishek commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :done, :_destroy])
Что такое `done`?

2019-09-19 08:39 UTC, aishek commented on app/models/link.rb
> +    return true if host&.include?('gist.github.com')
Эту и следующую строки можно сократить просто до `host&.include?('gist.github.com')`

2019-09-19 08:39 UTC, aishek commented on app/models/link.rb
> +    if gist?
Лучше воспользоваться "особым случаем":

```
def gist_id
  return unless gist?
  url.split('/').reject!(&:empty?).last
end
``

2019-09-19 08:39 UTC, aishek commented on app/models/answer.rb
> +  has_many :links, dependent: :destroy, as: :linkable, inverse_of: :linkable
Работа со ссылками просится в консерн

2019-09-19 08:39 UTC, aishek commented on app/models/answer.rb
> +      question.achievement.update!(user_id: self.user.id) if question.achievement.present?
Очень хорошо, но лучше объектами: `question.achievement.update!(user: self.user) if question.achievement.present?`

2019-09-19 08:39 UTC, aishek commented on app/views/achievements/index.html.slim
> +- @user_achievements.each do |award|
Я за `= render @user_achievements` и партиал

2019-09-19 08:39 UTC, aishek commented on app/views/answers/_answer.html.slim
> +        = f.fields_for :links do |link|
Просится в партиал

2019-09-19 08:39 UTC, aishek commented on app/views/questions/update.js.erb
> +      document.location.reload(true)
Что-то не нравятся мне эти штуки. Во-первых можно как-то так:

```
<% if question.links.any(&:gist?) %>
  document.location.reload(true)
<% end %>
```

Во-вторых, зачем это вообще?

2019-09-19 08:39 UTC, aishek commented on spec/controllers/links_controller_spec.rb
> +  describe 'DELETE #destroy' do
И проверки на рендеринг надо бы

2019-09-19 08:39 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +          end.to change(Achievement, :count).by(1)
Неплохо бы проверить что ачивка привязалась к вопросу

2019-09-19 08:39 UTC, aishek commented on spec/features/questions/add_link_when_edit_question_spec.rb
> +  scenario 'author of question deleted link', js: true do
Опечатка в названии?

2019-09-19 08:39 UTC, aishek commented on spec/features/questions/add_link_when_edit_question_spec.rb
> +  scenario 'author of question deleted link', js: true do
И надо проверить добавление ссылки на гист

2019-09-20 14:27 UTC, vkurennov approved these changes

2019-09-21 05:56 UTC, merged